// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCY89Y_h1L0gPWYR98gEJMTeJYWRoO9OHI',
    appId: '1:556652987989:web:f6e6951a3c6a48f59cf6dc',
    messagingSenderId: '556652987989',
    projectId: 'ai-app-8e111',
    authDomain: 'ai-app-8e111.firebaseapp.com',
    storageBucket: 'ai-app-8e111.firebasestorage.app',
    measurementId: 'G-N0B4QBGLQ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9hUHE2ptQNaFwhe80gM5AAoE8jPJHtnQ',
    appId: '1:556652987989:android:7744494b35b1de619cf6dc',
    messagingSenderId: '556652987989',
    projectId: 'ai-app-8e111',
    storageBucket: 'ai-app-8e111.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDue3ftWOXcSafHVnmOgo24y8Hk_0xXQ-k',
    appId: '1:556652987989:ios:afa233685896c21a9cf6dc',
    messagingSenderId: '556652987989',
    projectId: 'ai-app-8e111',
    storageBucket: 'ai-app-8e111.firebasestorage.app',
    iosClientId: '556652987989-csr2mjtddtomjrpl8g9fdl9l0girdd8e.apps.googleusercontent.com',
    iosBundleId: 'com.example.aiApp',
  );
}
